export const routes = {
    home: '/',
    login: '/login',
    listUser: '/admin/user',
    addUser: '/admin/user/add-user',
    updateUser: '/admin/user/updateUser',
    listCourse: '/admin/course',
    addCourse: '/admin/course/add-course',
    updateCourse: '/admin/course/update-course',
    listChapter: '/admin/chapter',
    addChapter: '/admin/chapter/add-chapter',
    updateChapter: '/admin/chapter/update-chapter',
    listLesson: '/admin/lesson',
    addLesson: '/admin/lesson/add-lesson',
    updateLesson: '/admin/lesson/update-lesson',
    listQuizze: '/admin/quizze',
    addQuizze: '/admin/quizze/add-quizze',
    updateQuizze: '/admin/quizze/update-quizze',
}
